site_name: Documentation
site_description: Documentation for Mirantis Secure Registry 4
site_author: Mirantis, Inc.

docs_dir: docs/
repo_name: MKE 4 Documentation
repo_url: https://github.com/Mirantis/msr-docs
edit_uri: https://github.com/Mirantis/msr-docs/edit/main/docs/

copyright:
  Copyright &copy; 2025 Mirantis Inc. - All rights reserved

theme:
  name: "material"
  palette:
    - scheme: default
      primary: black
      accent: black
  # highlightjs: true
  language: "en"
  # custom_dir: docs/custom_theme
  favicon: assets/favicon.svg
  logo: assets/mke-4k-inverted.svg
  
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - toc.autohide
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.tracking   # Anchor tracking
    - toc.follow            # Sidebar is automatically scrolled so that the active anchor is always visible
    - search.suggest        # Search suggestions
    - search.highlight      # Search highlights all occurrences after following the link
    # - content.action.edit
    - content.action.view
    - navigation.path       # Not working, for sponsors only
    - navigation.indexes
    # - navigation.tabs
    # - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css
  

extra_javascript:
  - javascripts/plausible.js            # this will be for metrics

plugins:
  - search
  - ezglossary:
      section_config:
        - name: demo
          inline_refs: short
  - macros:
      j2_variable_start_string: "{{{"
      j2_variable_end_string: "}}}"
  - exclude:
      glob:
        - "*.etag"
        - Dockerfile.serve-dev
        - Makefile*
        - requirements_pip.txt
        - requirements.txt
  - redirects:
      redirect_maps:
 
nav:
  - MSR 4 Documentation: index.md
  - Support, Services, Contact:
    - Overview: support/index.md
    - Get support: https://www.mirantis.com/support/enterprise-support-services/
    - Mirantis CloudCare Portal: https://support.mirantis.com/s/login/
    - Contact us: https://www.mirantis.com/contact/


markdown_extensions:
  - admonition
  - callouts
  - tables
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight: {}
  - pymdownx.inlinehilite: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 3
  - def_list

extra:
  repo_url: https://github.com/Mirantis/msr-docs
  docs_repo_name: Mirantis/docs
  generator: false
  base_url: ""
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/MirantisIT
      name: Mirantis on X
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/mirantisus
      name: Mirantis on YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mirantis
      name: Mirantis on LinkedIn
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/MirantisUS
      name: Mirantis on Facebook
  version:
    provider: mike
    default: stable
  analytics:
  docsVersionInfo:

