site_name: Claude Skills Marketplace
site_description: Mirantis Claude Skills Marketplace
site_author: Mirantis, Inc.
site_url: https://ai.mirantis.com/claude-skills/

docs_dir: docs/

copyright:
  Copyright &copy; 2026 Mirantis Inc. - All rights reserved

theme:
  name: "material"
  highlightjs: true
  custom_dir: docs/custom_theme
  language: "en"
  favicon: assets/msr-fav.png
  logo: assets/mirantis-logo-inverted.svg

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.tracking
    - toc.follow
    - content.action.view
    - navigation.indexes

extra_css:
  - stylesheets/extra.css
  - stylesheets/nav-decor.css
  - stylesheets/external-link.css

extra_javascript:
  - javascripts/plausible.js

plugins:
  - search
  - ezglossary:
      section_config:
        - name: demo
          inline_refs: short
  - macros:
      j2_variable_start_string: "{{{"
      j2_variable_end_string: "}}}"
  - exclude:
      glob:
        - "*.etag"
  - redirects:
      redirect_maps:

nav:
  - Home: index.md
  - Skills:
    - example-skill: skills/example-skill.md
    - example-mcp-python-skill: skills/example-mcp-python-skill.md
    - example-mcp-node-skill: skills/example-mcp-node-skill.md
    - markdown-doc-cleaner: skills/markdown-doc-cleaner.md

markdown_extensions:
  - admonition
  - callouts
  - tables
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight: {}
  - pymdownx.inlinehilite: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 3
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tasklist

extra:
  base_url: ""
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/MirantisIT
      name: Mirantis on X
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/mirantisus
      name: Mirantis on YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mirantis
      name: Mirantis on LinkedIn
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/MirantisUS
      name: Mirantis on Facebook
  version:
    provider: mike
    default: stable
