site_name: MSR Documentation
site_description: Documentation for Mirantis Secure Registry 4
site_author: Mirantis, Inc.

docs_dir: docs/
# repo_name: MSR 4 Documentation
# repo_url: https://github.com/Mirantis/msr-docs
# edit_uri: https://github.com/Mirantis/msr-docs/edit/main/docs/

copyright:
  Copyright &copy; 2025 Mirantis Inc. - All rights reserved

theme:
  name: "material"
  highlightjs: true
  custom_dir: docs/custom_theme
  language: "en"
  favicon: assets/msr-fav.png
  logo: assets/msr-4-inverted.svg
  
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
 #   - toc.autohide
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.tracking   # Anchor tracking
    - toc.follow            # Sidebar is automatically scrolled so that the active anchor is always visible
    - search.suggest        # Search suggestions
    - search.highlight      # Search highlights all occurrences after following the link
    # - content.action.edit
    - content.action.view
    - navigation.path       # Not working, for sponsors only
    - navigation.indexes
    # - navigation.tabs
    # - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css
  

extra_javascript:
  - javascripts/plausible.js            # this will be for metrics

plugins:
  - search
  - ezglossary:
      section_config:
        - name: demo
          inline_refs: short
  - macros:
      j2_variable_start_string: "{{{"
      j2_variable_end_string: "}}}"
  - exclude:
      glob:
        - "*.etag"
        - Dockerfile.serve-dev
        - Makefile*
        - requirements_pip.txt
        - requirements.txt
  - redirects:
      redirect_maps:

not_in_nav: |
    /common/*

nav:
  - MSR 4 Documentation: index.md
  - Product Overview: product-overview.md
  - MSR 4 Key Changes:
    - MSR 4 Key Changes: whats-new/index.md
    - Product Highlights: whats-new/product-highlights.md
    - Differences Between MSR Versions: whats-new/differences-between-versions.md
    - Removed Features: whats-new/removed-features.md
  - Architecture:
    - Architecture: architecture/index.md
    - Reference Architecture:
      - Reference Architecture: architecture/architecture-reference.md
      - Consumers Layer: architecture/architecture-reference/consumers-layer.md
      - Fundamental Services Layer: architecture/architecture-reference/fundamental-services-layer.md
      - Data Access Layer: architecture/architecture-reference/data-access-layer.md
      - Integration: architecture/architecture-reference/integration.md
    - Deployment:
      - Deployment: architecture/deployment/deployment.md
      - Deployment Options:
        - Deployment Options: architecture/deployment/deployment-options.md
        - All-in-one Deployment: architecture/deployment/all-in-one-deployment.md
        - High Availability Deployment:  architecture/deployment/ha-deployment.md
      - Components Deployment:
        - Components Deployment: architecture/deployment/components-deployment.md
        - Web Portal: architecture/deployment/web-portal.md
        - Proxy (API Routing): architecture/deployment/proxy.md
        - Core: architecture/deployment/core.md
        - Job Service: architecture/deployment/job-service.md
        - Registry: architecture/deployment/registry.md
        - Tivy: architecture/deployment/trivy.md
        - K-V storage: architecture/deployment/k-v-storage.md
        - SQL Database: architecture/deployment/sql-database.md
      - Deployment Resources:
        - Deployment Resources: architecture/deployment/deployment-resources.md
        - Harbor Helm Chart: architecture/deployment/harbor-helm-chart.md
        - Redis Helm Chart: architecture/deployment/redis-helm-chart.md
        - PostgreSQL Helm Chart: architecture/deployment/postgresql-helm-chart.md
      - System Requirements: architecture/system-reqs.md
      - Storage: architecture/storage.md
      - Networking: architecture/networking.md
      - Security:
        - Security: architecture/security/security.md
        - Kubernetes Security: architecture/security/kubernetes-security.md
        - Harbor Security: architecture/security/harbor-security.md
        - K-V Storage (Redis) Security: architecture/security/kv-storage-redis-security.md
        - DB Service (PostgreSQL) Security: architecture/security/db-service-security.md
        - Logging and Monitoring: architecture/security/logging-and-monitoring.md
        - Supply Chain: architecture/security/supply-chain.md
  - Installation Guide:
    - Installation Guide: installation/index.md
    - Prepare MKE 3.x for MSR Installation: installation/prepare-mke-for-msr-install.md
    - Prerequisites: installation/msr-system-reqs.md
    - Install MSR with High Availability:
        - Install MSR with High Availability: installation/installation-with-high-availability/index.md
        - Prerequisites: installation/installation-with-high-availability/ha-prerequisites.md
        - Install Helm: installation/installation-with-high-availability/ha-install-helm.md
        - Create PVC across Kubernetes workers: installation/installation-with-high-availability/ha-create-pvc-across-kubernetes-workers.md
        - Install highly available PostgreSQL: installation/installation-with-high-availability/ha-install-and-set-up-postgresql.md
        - Install highly available Redis: installation/installation-with-high-availability/ha-install-highly-available-redis.md
        - Install highly available MSR: installation/installation-with-high-availability/install-ha-msr.md
    - Install MSR single host using Docker Compose:
        - Install MSR single host using Docker Compose: installation/msr-docker-install/index.md
        - Prerequisites: installation/msr-docker-install/docker-compose-prerequisites.md
        - Install MSR using Docker Compose: installation/msr-docker-install/docker-compose-install.md
        - Manage MSR with Docker Compose: installation/msr-docker-install/manage-with-docker-compose.md
  - Operations Guide:
    - Operations Guide: operations/index.md
    - Authentication Configuration:
      - Authentication Configuration: operations/authentication-configuration/authentication-configuration.md
      - LDAP Authentication: operations/authentication-configuration/ldap-authentication.md
      - OIDC Authentication: operations/authentication-configuration/oidc-authentication.md
      - Database Authentication: operations/authentication-configuration/database-authentication.md
    - Configuring Replication: operations/configuring-replication.md
    - Configuring Webhooks: operations/configuring-webhooks.md
    - Log Rotation in Mirantis Secure Registry: operations/log-rotation.md
    - Managing Garbage Collection: operations/managing-garbage-collection.md
    - Managing Project Permissions: operations/managing-project-permissions.md
    - Managing Tag Retention Rules: operations/managing-tag-retention-rules.md
    - Metrics Collection and Visualization: operations/metrics.md
    - Mirror Images: operations/mirror-images.md
    - Signing Artifacts with Cosign: operations/signing-artifacts-with-cosign.md
    - Upgrade Guide: operations/upgrade.md
    - Vulnerability Scanning: operations/vulnerability-scanning.md
  - Backup Guide:
    - Backup Guide: backup/index.md
    - HA Backup:
      - HA Backup: backup/ha-backup/ha-backup.md
      - File System Backup vs Snapshot Backup: backup/ha-backup/system-backup-vs-snapshot-backup.md
      - Best Backup practices: backup/ha-backup/best-backup-practises.md
      - Monitoring Backup and Restore Status: backup/ha-backup/monitoring-backup-and-restore-status.md
      - Filesystem-Level Backups with Velero: backup/ha-backup/filesystem-level-backups-with-velero.md
      - Snapshot Backups with Velero: backup/ha-backup/snapshot-backups-with-velero.md
      - Schedule Backups and Restores: backup/ha-backup/automating-and-scheduling.md
    - Single Instance Backup: backup/instance-backup.md
    - Disaster Recovery:
      - Disaster Recovery: backup/disaster-recovery/index.md
      - NFS Metadata Restore:
        - NFS Metadata Restore: backup/disaster-recovery/nfs-metadata-restore/index.md
        - Install MinIO and Velero: backup/disaster-recovery/nfs-metadata-restore/metadata-install-minio-and-velero.md
        - Backup and Restore: backup/disaster-recovery/nfs-metadata-restore/metadata-restore-backup.md
      - NFS Full Restore:
        - NFS Full Restore: backup/disaster-recovery/nfs-full-restore/index.md
        - Install MinIO and Velero: backup/disaster-recovery/nfs-full-restore/full-install-minio-and-velero.md
        - Backup and Restore: backup/disaster-recovery/nfs-full-restore/full-restore-backup.md
  - Migration Guide:
    - Migration Guide: migration/index.md
    - Manual Migration:
      - Manual Migration: migration/manual-migration/index.md
      - Manual Migration Prerequisites: migration/manual-migration/manual-migration-prerequisites.md
      - Perform Migration: migration/manual-migration/migrate-msr.md
      - Post-Migration Configuration: migration/manual-migration/manual-configure-migration.md
    - Tool Migration:
      - Tool Migration: migration/tool-migration/index.md
      - What to Expect During the Migration: migration/tool-migration/what-to-expect-when-transitioning.md
      - Migration Prerequisites: migration/tool-migration/migration-prerequisites.md
      - Install Migration Tool: migration/tool-migration/install-migration-tool.md
      - Database Access Configuration: migration/tool-migration/db-configuration.md
      - Configure Migration Settings: migration/tool-migration/tool-configure-migration.md
      - Perform Migration:
        - Perform Migration: migration/tool-migration/perform-tool-migration.md
        - Migrate Projects: migration/tool-migration/partial-tool-migration/migrate-projects.md
        - Migrate Permissions: migration/tool-migration/partial-tool-migration/migrate-permissions.md
        - Migrate Push and Poll Mirroring Policies: migration/tool-migration/partial-tool-migration/migrate-push-poll-mirroring-policies.md
      - Validate Migration Data: migration/tool-migration/validate-migration-data.md
      - Post-Migration Configuration: migration/tool-migration/configure-migration-settings.md
      - Post-Migration Cleanup: migration/tool-migration/clean-up-after-migration.md
      - Migration Tool Reference:
        - Migration Tool Reference: migration/tool-migration/migration-tool-reference/index.md
        - Command Reference: migration/tool-migration/migration-tool-reference/command-reference.md
        - Configuration Reference: migration/tool-migration/migration-tool-reference/configuration-reference.md
      - Migration Tool Release Notes:
        - Migration Tool Release Notes: migration/tool-migration/migration-tool-release-notes/index.md
        - Migration Tool 1.3.0: migration/tool-migration/migration-tool-release-notes/1-3-0.md
        - Migration Tool 1.2.0: migration/tool-migration/migration-tool-release-notes/1-2-0.md
        - Migration Tool 1.1.0: migration/tool-migration/migration-tool-release-notes/1-1-0.md
        - Migration Tool 1.0.1: migration/tool-migration/migration-tool-release-notes/1-0-1.md
        - Migration Tool 1.0.0: migration/tool-migration/migration-tool-release-notes/1-0-0.md
  - Release Notes:
    - Release Notes: release-notes/index.md
    - 4.13.2:
      - 4.13.2: release-notes/4-13-2/index.md
      - Changelog: release-notes/4-13-2/changelog.md
      - Security information: release-notes/4-13-2/security-information.md
      - Known issues: release-notes/4-13-2/known-issues.md
    - 4.13.1:
      - 4.13.1: release-notes/4-13-1/index.md
      - Changelog: release-notes/4-13-1/changelog.md
      - Security information: release-notes/4-13-1/security-information.md
      - Known issues: release-notes/4-13-1/known-issues.md
    - 4-13-0:
      - 4.13.0: release-notes/4-13-0/index.md
      - Changelog: release-notes/4-13-0/changelog.md
      - Security information: release-notes/4-13-0/security-information.md
      - Known issues: release-notes/4-13-0/known-issues.md
  - Release Compatibility Matrix: compat-matrix.md
  - Release Cadence and Support Lifecycle: release-cadence-and-support-cycle.md
  - Support, Services, Contact:
    - Overview: support/index.md
    - Collect support bundles on MKE clusters: support/collect-support-bundles-on-mke-clusters.md
    - Get support: https://www.mirantis.com/support/enterprise-support-services/
    - Mirantis CloudCare Portal: https://support.mirantis.com/s/login/
    - Contact us: https://www.mirantis.com/contact/
  - MSR 2.9 Documentation (Legacy): https://docs.mirantis.com/msr/2.9/overview.html


markdown_extensions:
  - admonition
  - callouts
  - tables
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight: {}
  - pymdownx.inlinehilite: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 3
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tasklist
#  - pymdownx.extra
  - admonition

extra:
  # repo_url: https://github.com/Mirantis/msr-docs
  # docs_repo_name: Mirantis/docs
  # generator: false
  base_url: ""
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/MirantisIT
      name: Mirantis on X
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/mirantisus
      name: Mirantis on YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mirantis
      name: Mirantis on LinkedIn
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/MirantisUS
      name: Mirantis on Facebook
  version:
    provider: mike
    default: stable

    # Global variables

  latest_msr_4_13_tag: '4.13.2'
  latest_msr_4_0_tag: '4.0.2'
  latest_mke_tag: '3.8.8'
